export const catalogosFinancierosBase = {
  tiposMovimiento: ['Compra', 'Compra de animales', 'Inversion', 'Planilla', 'Venta de animales'],
  naturalezas: ['Egreso', 'Ingreso'],
  categorias: [
    'Alimentación',
    'Combustible',
    'Compras de animales',
    'Ganado',
    'Herramientas',
    'Infraestructura',
    'Mano de obra',
    'Mantenimiento',
    'Maquinaria',
    'Otros',
    'Porcinos',
    'Potreros',
    'Sanidad',
    'Ventas'
  ],
  unidades: ['L', 'KG', 'G', 'ML', 'UNIDAD', 'SACO', 'GALON', 'M', 'DOSIS'],
  tiposTrabajo: [
    'Alimentación',
    'Cerca',
    'Chapia',
    'Corral',
    'Fertilización',
    'Herbicida',
    'Limpieza',
    'Mantenimiento',
    'Mano de obra general',
    'Otro',
    'Sanidad',
    'Transporte'
  ],
  tiposInversion: [
    'Cercas',
    'Corrales',
    'Equipo',
    'Finca',
    'Ganado',
    'Infraestructura',
    'Maquinaria',
    'Mejora de potrero',
    'Otro',
    'Vehículo'
  ],
  destinosUso: [
    'Administración',
    'Aguas',
    'Alimentación',
    'Animal',
    'Camada',
    'Cerca',
    'Chapia',
    'Cortadora',
    'Finca',
    'Galera',
    'Mantenimiento',
    'Otro',
    'Potrero',
    'Rancho',
    'Sanidad',
    'Tractor'
  ],
  estadosActivo: ['En mantenimiento', 'En uso', 'Pendiente', 'Retirado', 'Vendido'],
  metodosPago: ['Cheque', 'Crédito', 'Efectivo', 'Otro', 'SINPE', 'Tarjeta', 'Transferencia'],
  monedas: ['CRC', 'USD']
};
