export const catalogosFinancierosBase = {
  tiposMovimiento: ['Planilla', 'Inversion', 'Compra'],
  naturalezas: ['Ingreso', 'Egreso'],
  categorias: [
    'Alimentación',
    'Sanidad',
    'Combustible',
    'Mano de obra',
    'Potreros',
    'Infraestructura',
    'Herramientas',
    'Maquinaria',
    'Mantenimiento',
    'Ganado',
    'Porcinos',
    'Ventas',
    'Compras de animales',
    'Otros'
  ],
  unidades: ['L', 'KG', 'G', 'ML', 'UNIDAD', 'SACO', 'GALON', 'M', 'DOSIS'],
  tiposTrabajo: [
    'Chapia',
    'Herbicida',
    'Fertilización',
    'Cerca',
    'Corral',
    'Mantenimiento',
    'Limpieza',
    'Alimentación',
    'Sanidad',
    'Transporte',
    'Mano de obra general',
    'Otro'
  ],
  tiposInversion: [
    'Ganado',
    'Finca',
    'Infraestructura',
    'Cercas',
    'Corrales',
    'Maquinaria',
    'Equipo',
    'Vehículo',
    'Mejora de potrero',
    'Otro'
  ],
  destinosUso: [
    'Chapia',
    'Tractor',
    'Galera',
    'Cortadora',
    'Cerca',
    'Rancho',
    'Aguas',
    'Sanidad',
    'Potrero',
    'Mantenimiento',
    'Alimentación',
    'Camada',
    'Animal',
    'Finca',
    'Administración',
    'Otro'
  ],
  estadosActivo: ['En uso', 'Pendiente', 'En mantenimiento', 'Vendido', 'Retirado'],
  metodosPago: ['Efectivo', 'Transferencia', 'SINPE', 'Tarjeta', 'Cheque', 'Crédito', 'Otro'],
  monedas: ['CRC', 'USD']
};
